#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 
# @Author  : lidong@immusician.com
# @Site    :
# @File    :

# purchased

decode_success = {'version': '1.0', 'packageName': 'com.okmusician.android', 'eventTimeMillis': '1562896549434', 'subscriptionNotification': {'version': '1.0', 'notificationType': 4, 'purchaseToken': 'dnhbfeelleahlfgnpippambi.AO-J1OwtMBJzo319B70em2YMUPUg_juI9keSc9EbYUiv7tydbLu-LMJ8xYwAfUxPBuYkElcE3u436r7Ol0rI_1usDVnsfUatfzXf76IOtKYcalrEXb_9Re3CuE29ygWQZiEyVi6jU1GS_eysR6_2o0S9ny7bXRcAZA', 'subscriptionId': 'okmusician.monthly.guitar'}}
google_order_info = {'error': 0, 'msg': 'OK', 'data': {'kind': 'androidpublisher#subscriptionPurchase', 'startTimeMillis': '1562896547711', 'expiryTimeMillis': '1562896957831', 'autoRenewing': True, 'priceCurrencyCode': 'USD', 'priceAmountMicros': '9990000', 'countryCode': 'HK', 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'paymentState': 1, 'orderId': 'GPA.3324-1182-0255-83393', 'purchaseType': 0, 'acknowledgementState': 1}}
purchase_receipt = {"Store":"GooglePlay","TransactionID":"GPA.3324-1182-0255-83393","Payload":"{\"json\":\"{\\\"orderId\\\":\\\"GPA.3324-1182-0255-83393\\\",\\\"packageName\\\":\\\"com.okmusician.android\\\",\\\"productId\\\":\\\"okmusician.monthly.guitar\\\",\\\"purchaseTime\\\":1562896547711,\\\"purchaseState\\\":0,\\\"developerPayload\\\":\\\"{\\\\\\\"developerPayload\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"is_free_trial\\\\\\\":false,\\\\\\\"has_introductory_price_trial\\\\\\\":false,\\\\\\\"is_updated\\\\\\\":false}\\\",\\\"purchaseToken\\\":\\\"dnhbfeelleahlfgnpippambi.AO-J1OwtMBJzo319B70em2YMUPUg_juI9keSc9EbYUiv7tydbLu-LMJ8xYwAfUxPBuYkElcE3u436r7Ol0rI_1usDVnsfUatfzXf76IOtKYcalrEXb_9Re3CuE29ygWQZiEyVi6jU1GS_eysR6_2o0S9ny7bXRcAZA\\\",\\\"autoRenewing\\\":true}\",\"signature\":\"XOJ5ENgDh\\/x2dgOrNakywXUtuTntS7kVRyVqgG3EeyHqA1awVdAqw\\/KySJXnbcOX16g9wPOiBSt14+kg\\/B0U3XZA6LagWdPqn4hCbyePOre8ws+Xy1lt7PEZoLvlSmP6FILhXZDjAGI5JaEzsyuqLgfq2c+v0N\\/T7YreCMXa2SvnJemhZF+8qMCrmPTqinwre6aO2WtY+HNMr8oWDZT8Q2sbtSLaOJ31goHnOOt8nvcmQAI3AOZ5qMDQ2kQhxiDiZ04AP+JP0lChxLEix\\/\\/T\\/VOieLJVWWQqNiAcZwBlEc6PDGyYighW4su0AR07rxzwp7wW70yJ8MtKUCZ2obF+4A==\",\"skuDetails\":\"{\\\"skuDetailsToken\\\":\\\"AEuhp4Lnf8xDf5dm2I1LPGdgr9zeyVfbXNHjcvgX2aHfKru7EMVrNOqrrCG_7OsBa34=\\\",\\\"productId\\\":\\\"okmusician.monthly.guitar\\\",\\\"type\\\":\\\"subs\\\",\\\"price\\\":\\\"HK$78.00\\\",\\\"price_amount_micros\\\":78000000,\\\"price_currency_code\\\":\\\"HKD\\\",\\\"subscriptionPeriod\\\":\\\"P1M\\\",\\\"freeTrialPeriod\\\":\\\"P3D\\\",\\\"title\\\":\\\"Monthly Subscription for Guitar (OKMusician)\\\",\\\"description\\\":\\\"Fully access Guitar Lessons, Songs, Chord Library and Reverse Chord Finder.\\\"}\",\"isPurchaseHistorySupported\":true}"}


decode_success_s = {'version': '1.0', 'packageName': 'com.okmusician.android', 'eventTimeMillis': '1562896624322', 'subscriptionNotification': {'version': '1.0', 'notificationType': 4, 'purchaseToken': 'nojkekcccknhpmjemhmkaeic.AO-J1OzvQRseVcrXePMkcK_-8q-373kj19DtIKmr4B3q6NkWTS_AQzVStlKnW9d_pw-8VzqzC_0EBFWde-N_zqVsY-2YYAa0rxrq0HWmmZRJZ0vVJSRkKiGLdve2U3cQCfx9P4nBelPrtqFWLZrLEXvg51MKPMMs4Q', 'subscriptionId': 'okmusician.monthly.ukulele'}}
google_order_info_s = {'error': 0, 'msg': 'OK', 'data': {'kind': 'androidpublisher#subscriptionPurchase', 'startTimeMillis': '1562896623439', 'expiryTimeMillis': '1562897034353', 'autoRenewing': True, 'priceCurrencyCode': 'USD', 'priceAmountMicros': '9990000', 'countryCode': 'HK', 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'paymentState': 1, 'orderId': 'GPA.3320-1873-9407-93921', 'purchaseType': 0, 'acknowledgementState': 1}}

purchase_receipt_s = {"Store":"GooglePlay","TransactionID":"GPA.3320-1873-9407-93921","Payload":"{\"json\":\"{\\\"orderId\\\":\\\"GPA.3320-1873-9407-93921\\\",\\\"packageName\\\":\\\"com.okmusician.android\\\",\\\"productId\\\":\\\"okmusician.monthly.ukulele\\\",\\\"purchaseTime\\\":1562896623439,\\\"purchaseState\\\":0,\\\"developerPayload\\\":\\\"{\\\\\\\"developerPayload\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"is_free_trial\\\\\\\":false,\\\\\\\"has_introductory_price_trial\\\\\\\":false,\\\\\\\"is_updated\\\\\\\":false}\\\",\\\"purchaseToken\\\":\\\"nojkekcccknhpmjemhmkaeic.AO-J1OzvQRseVcrXePMkcK_-8q-373kj19DtIKmr4B3q6NkWTS_AQzVStlKnW9d_pw-8VzqzC_0EBFWde-N_zqVsY-2YYAa0rxrq0HWmmZRJZ0vVJSRkKiGLdve2U3cQCfx9P4nBelPrtqFWLZrLEXvg51MKPMMs4Q\\\",\\\"autoRenewing\\\":true}\",\"signature\":\"A9NsMyVHE4HT2cMOlW8FbzMxqY2HbUrmoGJLesB9v+jvw7Dx+9YjbX2gkmVja2oYuvr7zGkRe+W\\/F79p4cZuNsh8yziiUN3g44+LABqhPJpOIiGRDh5z8qtBIansA5mLffml\\/BVuyGfX2L94H06AQA2H1LJ9h06DKVPsTCrSYQNqc3wJU7ezmmJtOhuEdlalxQ4xBnA1n65YywZJ+9Pfhs58Mt\\/9o6mSG2VSaey\\/t555VeXPozBdq5YXq2B8shplDo65TMeXSNmznXZb3jxxQyOw94Q12wjNXllqawuvKyAdjewvOKBMJxsqKj38Zfrf\\/R8eaWgmR\\/3QGaf3pXADdA==\",\"skuDetails\":\"{\\\"skuDetailsToken\\\":\\\"AEuhp4JLXXc6ye2rtCpwfI_vJcNGeJ3Xhb_0sqN9rqZw0diYMMk3VIE6hUZhteitc74=\\\",\\\"productId\\\":\\\"okmusician.monthly.ukulele\\\",\\\"type\\\":\\\"subs\\\",\\\"price\\\":\\\"HK$78.00\\\",\\\"price_amount_micros\\\":78000000,\\\"price_currency_code\\\":\\\"HKD\\\",\\\"subscriptionPeriod\\\":\\\"P1M\\\",\\\"freeTrialPeriod\\\":\\\"P3D\\\",\\\"title\\\":\\\"Monthly Subscription for Ukulele (OKMusician)\\\",\\\"description\\\":\\\"Fully access ukulele courses, songs, chord library and reverse chord finder.\\\"}\",\"isPurchaseHistorySupported\":true}"}
