#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 
# @Author  : lidong@immusician.com
# @Site    :
# @File    :
import datetime

a = {'is_delete': False, 'updated_at': 1564211806, 'autoRenewing': True, 'orderId': 'GPA.3342-2167-7425-48839', 'packageName': 'com.okmusician.android', 'product_id': 'okmusician.monthly.guitar', 'purchaseTime': 1562596624964, 'purchaseState': 0, 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'purchaseToken': 'nkeklojppeoelmbcghlgoclb.AO-J1Oxg9SNmKmupxLfAlVML_n0_uBpXKBqposU-bGw5hmxJ4enwn3-yHJsV8FvY6498RbbhHJmY-qZtzpqK0hh1bt_dHCzzVg4YqsM10W5KWvdjI2nVLkRc3TmGCaWRupK-evi2QetQnCf-HOiWWi2vMr8ZIYSUVw', 'subscriber': 519, 'linkedPurchaseToken': None, 'acknowledgementState': None, 'kind': None, 'startTimeMillis': None, 'expiryTimeMillis': None, 'priceCurrencyCode': None, 'priceAmountMicros': None, 'countryCode': None, 'paymentState': None, 'purchaseType': None, 'cancelReason': None, 'userCancellationTimeMillis': None, 'expires_date': None, 'original_order_id': 'GPA.3342-2167-7425-48839'}

aa = {'is_delete': False, 'updated_at': 1564212012, 'autoRenewing': True, 'orderId': 'GPA.3342-2167-7425-48839', 'packageName': 'com.okmusician.android', 'product_id': 'okmusician.monthly.guitar', 'purchaseTime': 1562596624964, 'purchaseState': 0, 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'purchaseToken': 'nkeklojppeoelmbcghlgoclb.AO-J1Oxg9SNmKmupxLfAlVML_n0_uBpXKBqposU-bGw5hmxJ4enwn3-yHJsV8FvY6498RbbhHJmY-qZtzpqK0hh1bt_dHCzzVg4YqsM10W5KWvdjI2nVLkRc3TmGCaWRupK-evi2QetQnCf-HOiWWi2vMr8ZIYSUVw', 'subscriber': 519, 'linkedPurchaseToken': None, 'acknowledgementState': None, 'kind': None, 'startTimeMillis': None, 'expiryTimeMillis': None, 'priceCurrencyCode': None, 'priceAmountMicros': None, 'countryCode': None, 'paymentState': None, 'purchaseType': None, 'cancelReason': None, 'userCancellationTimeMillis': None, 'expires_date': None, 'original_order_id': 'GPA.3342-2167-7425-48839'}

b = {'is_delete': False, 'updated_at': datetime.datetime(2019, 7, 27, 7, 16, 46), 'autoRenewing': True, 'orderId': 'GPA.3342-2167-7425-48839', 'packageName': 'com.okmusician.android', 'product_id': 'okmusician.monthly.guitar', 'purchaseTime': 1562596624964, 'purchaseState': 0, 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'purchaseToken': 'nkeklojppeoelmbcghlgoclb.AO-J1Oxg9SNmKmupxLfAlVML_n0_uBpXKBqposU-bGw5hmxJ4enwn3-yHJsV8FvY6498RbbhHJmY-qZtzpqK0hh1bt_dHCzzVg4YqsM10W5KWvdjI2nVLkRc3TmGCaWRupK-evi2QetQnCf-HOiWWi2vMr8ZIYSUVw', 'subscriber': 519, 'linkedPurchaseToken': None, 'acknowledgementState': None, 'kind': None, 'startTimeMillis': None, 'expiryTimeMillis': None, 'priceCurrencyCode': None, 'priceAmountMicros': None, 'countryCode': None, 'paymentState': None, 'purchaseType': None, 'cancelReason': None, 'userCancellationTimeMillis': None, 'expires_date': None, 'original_order_id': 'GPA.3342-2167-7425-48839'}

bb = {'is_delete': False, 'updated_at': datetime.datetime(2019, 7, 27, 7, 20, 12), 'autoRenewing': True, 'orderId': 'GPA.3342-2167-7425-48839', 'packageName': 'com.okmusician.android', 'product_id': 'okmusician.monthly.guitar', 'purchaseTime': 1562596624964, 'purchaseState': 0, 'developerPayload': '{"developerPayload":"","is_free_trial":false,"has_introductory_price_trial":false,"is_updated":false}', 'purchaseToken': 'nkeklojppeoelmbcghlgoclb.AO-J1Oxg9SNmKmupxLfAlVML_n0_uBpXKBqposU-bGw5hmxJ4enwn3-yHJsV8FvY6498RbbhHJmY-qZtzpqK0hh1bt_dHCzzVg4YqsM10W5KWvdjI2nVLkRc3TmGCaWRupK-evi2QetQnCf-HOiWWi2vMr8ZIYSUVw', 'subscriber': 519, 'linkedPurchaseToken': None, 'acknowledgementState': None, 'kind': None, 'startTimeMillis': None, 'expiryTimeMillis': None, 'priceCurrencyCode': None, 'priceAmountMicros': None, 'countryCode': None, 'paymentState': None, 'purchaseType': None, 'cancelReason': None, 'userCancellationTimeMillis': None, 'expires_date': None, 'original_order_id': 'GPA.3342-2167-7425-48839'}
