# # #
# # #
# # # #
# # # # lis = "112132113".split(",")
# # # # print(lis)
# # #
# # #
# # # import time
# # #
# # # old = "2019-1-8"
# # # tuple_time = time.strptime(old, "%Y-%m-%d")
# # # stamp_time = time.mktime(tuple_time)
# # # print(stamp_time)
# #
# # # a = "4"
# #
# # # import random
# # #
# # # ret = random.randrange(0, 1798)
# # # print(ret, type(ret))
# # #
# # # dic = {}
# # # dic.pop()
# #
# # d = [
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "_id" : 1
# #         },
# #         "name" : "_id_",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "_fts" : "text",
# #             "_ftsx" : 1
# #         },
# #         "name" : "name_text_author_text_key_words_text",
# #         "ns" : "piano.v1_score",
# #         "weights" : {
# #             "author" : 1,
# #             "key_words" : 1,
# #             "name" : 1
# #         },
# #         "default_language" : "english",
# #         "language_override" : "language",
# #         "textIndexVersion" : 2
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "category" : 1
# #         },
# #         "name" : "category_1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "diff" : 1
# #         },
# #         "name" : "diff_1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "bgt" : 1
# #         },
# #         "name" : "bgt_1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "hot" : -1
# #         },
# #         "name" : "hot_-1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "bgt" : 1,
# #             "hot" : -1
# #         },
# #         "name" : "bgt_1_hot_-1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "is_vip" : -1,
# #             "is_vip_tmp" : -1,
# #             "hot" : -1
# #         },
# #         "name" : "is_vip_-1_is_vip_tmp_-1_hot_-1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "is_vip" : 1
# #         },
# #         "name" : "is_vip_1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "is_vip_tmp" : 1
# #         },
# #         "name" : "is_vip_tmp_1",
# #         "ns" : "piano.v1_score"
# #     },
# #     {
# #         "v" : 2,
# #         "key" : {
# #             "add_time" : -1.0,
# #             "updated_at" : -1.0
# #         },
# #         "name" : "add_time_-1_updated_at_-1",
# #         "ns" : "piano.v1_score"
# #     }
# # ]document
# #
# # print(len(d))
#
#
# import time
#
# print(time.time())
#
#
# def func(item):
#     if item:
#         yield 1
#     return
# print(next(func(1)))

# lis = [
#     {
#         "v" : 1,
#         "key" : {
#             "_id" : 1
#         },
#         "name" : "_id_",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "_fts" : "text",
#             "_ftsx" : 1
#         },
#         "name" : "name_text_author_text_key_words_text",
#         "ns" : "piano.v1_score",
#         "weights" : {
#             "author" : 1,
#             "key_words" : 1,
#             "name" : 1
#         },
#         "default_language" : "english",
#         "language_override" : "language",
#         "textIndexVersion" : 2
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "category" : 1
#         },
#         "name" : "category_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "hot" : 1.0
#         },
#         "name" : "hot_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "add_time" : 1.0
#         },
#         "name" : "add_time_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "diff" : 1.0
#         },
#         "name" : "diff_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "bgt" : 1.0
#         },
#         "name" : "bgt_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "hot" : -1.0
#         },
#         "name" : "hot_-1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "state" : 1.0,
#             "add_time" : -1.0
#         },
#         "name" : "state_1_add_time_-1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "add_time" : -1.0,
#             "hot" : -1.0
#         },
#         "name" : "add_time_-1_hot_-1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "bgt" : 1.0,
#             "hot" : -1.0
#         },
#         "name" : "bgt_1_hot_-1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "is_vip" : -1.0,
#             "is_vip_tmp" : -1.0,
#             "hot" : -1.0
#         },
#         "name" : "is_vip_-1_is_vip_tmp_-1_hot_-1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "is_vip" : 1.0
#         },
#         "name" : "is_vip_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "is_vip_tmp" : 1.0
#         },
#         "name" : "is_vip_tmp_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "instrument" : 1.0
#         },
#         "name" : "instrument_1",
#         "ns" : "piano.v1_score"
#     },
#     {
#         "v" : 1,
#         "key" : {
#             "instrument" : 1.0,
#             "bgt" : 1.0
#         },
#         "name" : "instrument_1_bgt_1",
#         "ns" : "piano.v1_score"
#     }
# ]
# language = ""
# print(f"{language}:settings")

import requests, json

headers = {
    "content-type": "application/json",
    "UID": '410',
    "Token": "GOD"
}
ret = {"Store": "AppleAppStore", "TransactionID": "1000000543129420",
       "Payload": "MIJE9gYJKoZIhvcNAQcCoIJE5zCCROMCAQExCzAJBgUrDgMCGgUAMII0lwYJKoZIhvcNAQcBoII0iASCNIQxgjSAMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgEDAgEBBAMMATEwCwIBCwIBAQQDAgEAMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQoCAQEEBBYCNCswDAIBDgIBAQQEAgIAnzANAgENAgEBBAUCAwHV7TANAgETAgEBBAUMAzEuMDAOAgEJAgEBBAYCBFAyNTIwGAIBBAIBAgQQ/Kmu/B+d0A5rS+upMzXNSjAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBwCAQICAQEEFAwSY29tLm9rbXVzaWNpYW4uaW9zMBwCAQUCAQEEFLwHCe5AK1iOOLP10iBggvG/ZVPyMB4CAQwCAQEEFhYUMjAxOS0wNy0wM1QxMDowNDozMFowHgIBEgIBAQQWFhQyMDEzLTA4LTAxVDA3OjAwOjAwWjBCAgEHAgEBBDp26Y8jVB0F+xwcj8iQnH1Anv8gsjnAB/CDUsp7Itar5aVfKFIotefl0V+fZwl3HEkdoRHupll7iZkDMFcCAQYCAQEET8JQBvkCweeMDbMzYIVXnQGGLorANMzQcxVA9UUMeTxZiUHMKHjHRDNLHW5Q73tHZk/yZ/8j3LDY2iFdvJoAdasXMYhxZ60lW78ugyAmOGswggGBAgERAgEBBIIBdzGCAXMwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncIckMBsCAganAgEBBBIMEDEwMDAwMDA1MzMwNTAwMzcwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGpgIBAQQWDBRva211c2ljYW4uYWxsLnllYXJseTAfAgIGqAIBAQQWFhQyMDE5LTA1LTMxVDAxOjIyOjM1WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA1LTMxVDAyOjIyOjM1WjCCAYECARECAQEEggF3MYIBczALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqdwptQwGwICBqcCAQEEEgwQMTAwMDAwMDUzMzA2NTQ2MjAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgamAgEBBBYMFG9rbXVzaWNhbi5hbGwueWVhcmx5MB8CAgaoAgEBBBYWFDIwMTktMDUtMzFUMDI6NDA6MzFaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDUtMzFUMDM6NDA6MzFaMIIBgQIBEQIBAQSCAXcxggFzMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3CnDTAbAgIGpwIBAQQSDBAxMDAwMDAwNTMzMDc5NTUyMBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqYCAQEEFgwUb2ttdXNpY2FuLmFsbC55ZWFybHkwHwICBqgCAQEEFhYUMjAxOS0wNS0zMVQwMzo0MDozMVowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNS0zMVQwNDo0MDozMVowggGBAgERAgEBBIIBdzGCAXMwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncKlVMBsCAganAgEBBBIMEDEwMDAwMDA1MzQyMDM1ODEwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGpgIBAQQWDBRva211c2ljYW4uYWxsLnllYXJseTAfAgIGqAIBAQQWFhQyMDE5LTA2LTA0VDIyOjUzOjI0WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTA0VDIzOjUzOjI0WjCCAYECARECAQEEggF3MYIBczALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqdxtnUwGwICBqcCAQEEEgwQMTAwMDAwMDUzNDIwNzc0MzAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgamAgEBBBYMFG9rbXVzaWNhbi5hbGwueWVhcmx5MB8CAgaoAgEBBBYWFDIwMTktMDYtMDRUMjM6NTM6MjRaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMDVUMDA6NTM6MjRaMIIBgQIBEQIBAQSCAXcxggFzMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3G4zDAbAgIGpwIBAQQSDBAxMDAwMDAwNTM0MjEyNzA2MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqYCAQEEFgwUb2ttdXNpY2FuLmFsbC55ZWFybHkwHwICBqgCAQEEFhYUMjAxOS0wNi0wNVQwMDo1MzoyNFowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0wNVQwMTo1MzoyNFowggGBAgERAgEBBIIBdzGCAXMwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncbp5MBsCAganAgEBBBIMEDEwMDAwMDA1MzQyMjE4MzAwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGpgIBAQQWDBRva211c2ljYW4uYWxsLnllYXJseTAfAgIGqAIBAQQWFhQyMDE5LTA2LTA1VDAxOjUzOjI0WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTA1VDAyOjUzOjI0WjCCAYECARECAQEEggF3MYIBczALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqdxvJYwGwICBqcCAQEEEgwQMTAwMDAwMDUzNDIzMDY1ODAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgamAgEBBBYMFG9rbXVzaWNhbi5hbGwueWVhcmx5MB8CAgaoAgEBBBYWFDIwMTktMDYtMDVUMDI6NTM6MjRaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMDVUMDM6NTM6MjRaMIIBgQIBEQIBAQSCAXcxggFzMAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3G/szAbAgIGpwIBAQQSDBAxMDAwMDAwNTM0MjQyNzQ2MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqYCAQEEFgwUb2ttdXNpY2FuLmFsbC55ZWFybHkwHwICBqgCAQEEFhYUMjAxOS0wNi0wNVQwMzo1MzoyNFowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0wNVQwNDo1MzoyNFowggGCAgERAgEBBIIBeDGCAXQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncIcJMBsCAganAgEBBBIMEDEwMDAwMDA1MzI5MDE2OTYwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ3OjEwWjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA1LTMwVDEyOjUyOjEwWjAgAgIGpgIBAQQXDBVva211c2ljYW4uYWxsLm1vbnRobHkwggGCAgERAgEBBIIBeDGCAXQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncKSeMBsCAganAgEBBBIMEDEwMDAwMDA1MzMwNjQ1MzcwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA1LTMxVDAyOjM1OjMxWjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA1LTMxVDAyOjQwOjMxWjAgAgIGpgIBAQQXDBVva211c2ljYW4uYWxsLm1vbnRobHkwggGCAgERAgEBBIIBeDGCAXQwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQEwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ncIcIMBsCAganAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ3OjEwWjAgAgIGpgIBAQQXDBVva211c2ljYW4uYWxsLm1vbnRobHkwggGDAgERAgEBBIIBeTGCAXUwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6neWmlMBsCAganAgEBBBIMEDEwMDAwMDA1NDE3NzUyNDAwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA2LTI4VDEzOjA2OjQzWjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTI4VDEzOjExOjQzWjAhAgIGpgIBAQQYDBZva211c2ljaWFuLm1vbnRobHkuYWxsMIIBgwIBEQIBAQSCAXkxggF1MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3o0VTAbAgIGpwIBAQQSDBAxMDAwMDAwNTQxNzc2NzA4MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNi0yOFQxMzoxMTo0M1owHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0yOFQxMzoxNjo0M1owIQICBqYCAQEEGAwWb2ttdXNpY2lhbi5tb250aGx5LmFsbDCCAYMCARECAQEEggF5MYIBdTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd6NLcwGwICBqcCAQEEEgwQMTAwMDAwMDU0MTc3ODkxOTAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDYtMjhUMTM6MTY6NDNaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMjhUMTM6MjE6NDNaMCECAgamAgEBBBgMFm9rbXVzaWNpYW4ubW9udGhseS5hbGwwggGDAgERAgEBBIIBeTGCAXUwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nejUnMBsCAganAgEBBBIMEDEwMDAwMDA1NDE3ODAyNjUwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA2LTI4VDEzOjIxOjQzWjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTI4VDEzOjI2OjQzWjAhAgIGpgIBAQQYDBZva211c2ljaWFuLm1vbnRobHkuYWxsMIIBgwIBEQIBAQSCAXkxggF1MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3o1kTAbAgIGpwIBAQQSDBAxMDAwMDAwNTQxNzgxNTM5MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNi0yOFQxMzoyNjo0M1owHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0yOFQxMzozMTo0M1owIQICBqYCAQEEGAwWb2ttdXNpY2lhbi5tb250aGx5LmFsbDCCAYMCARECAQEEggF5MYIBdTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd6Nf0wGwICBqcCAQEEEgwQMTAwMDAwMDU0MTc4NDE0ODAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDYtMjhUMTM6MzE6NDNaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMjhUMTM6MzY6NDNaMCECAgamAgEBBBgMFm9rbXVzaWNpYW4ubW9udGhseS5hbGwwggGDAgERAgEBBIIBeTGCAXUwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6nejaDMBsCAganAgEBBBIMEDEwMDAwMDA1NDE3ODc0OTAwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA2LTI4VDEzOjM5OjA1WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTI4VDEzOjQ0OjA1WjAhAgIGpgIBAQQYDBZva211c2ljaWFuLm1vbnRobHkuYWxsMIIBhgIBEQIBAQSCAXwxggF4MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3HE9TAbAgIGpwIBAQQSDBAxMDAwMDAwNTQxMjYyMDU0MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNi0yN1QxMToxMjo1N1owHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0yN1QxMToxNzo1N1owJAICBqYCAQEEGwwZb2ttdXNpY2lhbi5tb250aGx5Lmd1aXRhcjCCAYYCARECAQEEggF8MYIBeDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd5ZZgwGwICBqcCAQEEEgwQMTAwMDAwMDU0MTI2MzcwODAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDYtMjdUMTE6MTc6NTdaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMjdUMTE6MjI6NTdaMCQCAgamAgEBBBsMGW9rbXVzaWNpYW4ubW9udGhseS5ndWl0YXIwggGGAgERAgEBBIIBfDGCAXgwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6neWX1MBsCAganAgEBBBIMEDEwMDAwMDA1NDEyNjcwNDIwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA2LTI3VDExOjIyOjU3WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTI3VDExOjI3OjU3WjAkAgIGpgIBAQQbDBlva211c2ljaWFuLm1vbnRobHkuZ3VpdGFyMIIBhgIBEQIBAQSCAXwxggF4MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3lm7DAbAgIGpwIBAQQSDBAxMDAwMDAwNTQxMjcxNTg4MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNi0yN1QxMToyNzo1N1owHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNi0yN1QxMTozMjo1N1owJAICBqYCAQEEGwwZb2ttdXNpY2lhbi5tb250aGx5Lmd1aXRhcjCCAYYCARECAQEEggF8MYIBeDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd5Z/AwGwICBqcCAQEEEgwQMTAwMDAwMDU0MTI3MzYxMDAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDYtMjdUMTE6MzI6NTdaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDYtMjdUMTE6Mzc6NTdaMCQCAgamAgEBBBsMGW9rbXVzaWNpYW4ubW9udGhseS5ndWl0YXIwggGGAgERAgEBBIIBfDGCAXgwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6neWjFMBsCAganAgEBBBIMEDEwMDAwMDA1NDEyNzYxOTYwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA2LTI3VDExOjM3OjU3WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA2LTI3VDExOjQyOjU3WjAkAgIGpgIBAQQbDBlva211c2ljaWFuLm1vbnRobHkuZ3VpdGFyMIIBhgIBEQIBAQSCAXwxggF4MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3uZ5zAbAgIGpwIBAQQSDBAxMDAwMDAwNTQzMTA4MzMzMBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNy0wM1QwOTozMzo1MVowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNy0wM1QwOTozODo1MVowJAICBqYCAQEEGwwZb2ttdXNpY2lhbi5tb250aGx5Lmd1aXRhcjCCAYYCARECAQEEggF8MYIBeDALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd7mncwGwICBqcCAQEEEgwQMTAwMDAwMDU0MzExMTA4MjAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDctMDNUMDk6Mzg6NTFaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDctMDNUMDk6NDM6NTFaMCQCAgamAgEBBBsMGW9rbXVzaWNpYW4ubW9udGhseS5ndWl0YXIwggGGAgERAgEBBIIBfDGCAXgwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ne5r9MBsCAganAgEBBBIMEDEwMDAwMDA1NDMxMTkzNTkwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA3LTAzVDA5OjUwOjQ5WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA3LTAzVDA5OjU1OjQ5WjAkAgIGpgIBAQQbDBlva211c2ljaWFuLm1vbnRobHkuZ3VpdGFyMIIBhgIBEQIBAQSCAXwxggF4MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3ucmjAbAgIGpwIBAQQSDBAxMDAwMDAwNTQzMTI5NDIwMBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNy0wM1QxMDowNDoyOFowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNy0wM1QxMDowOToyOFowJAICBqYCAQEEGwwZb2ttdXNpY2lhbi5tb250aGx5Lmd1aXRhcjCCAYcCARECAQEEggF9MYIBeTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd6N0swGwICBqcCAQEEEgwQMTAwMDAwMDU0MzA5NzU4OTAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDctMDNUMDk6MTU6MjRaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDctMDNUMDk6MjA6MjRaMCUCAgamAgEBBBwMGm9rbXVzaWNpYW4ubW9udGhseS51a3VsZWxlMIIBhwIBEQIBAQSCAX0xggF5MAsCAgatAgEBBAIMADALAgIGsAIBAQQCFgAwCwICBrICAQEEAgwAMAsCAgazAgEBBAIMADALAgIGtAIBAQQCDAAwCwICBrUCAQEEAgwAMAsCAga2AgEBBAIMADAMAgIGpQIBAQQDAgEBMAwCAgarAgEBBAMCAQMwDAICBq4CAQEEAwIBADAMAgIGsQIBAQQDAgEAMAwCAga3AgEBBAMCAQAwEgICBq8CAQEECQIHA41+p3uYSjAbAgIGpwIBAQQSDBAxMDAwMDAwNTQzMDk5OTE0MBsCAgapAgEBBBIMEDEwMDAwMDA1MzI5MDEwMTQwHwICBqgCAQEEFhYUMjAxOS0wNy0wM1QwOToyMDoyNFowHwICBqoCAQEEFhYUMjAxOS0wNS0zMFQxMjo0NToxMFowHwICBqwCAQEEFhYUMjAxOS0wNy0wM1QwOToyNToyNFowJQICBqYCAQEEHAwab2ttdXNpY2lhbi5tb250aGx5LnVrdWxlbGUwggGHAgERAgEBBIIBfTGCAXkwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAzAMAgIGrgIBAQQDAgEAMAwCAgaxAgEBBAMCAQAwDAICBrcCAQEEAwIBADASAgIGrwIBAQQJAgcDjX6ne5i5MBsCAganAgEBBBIMEDEwMDAwMDA1NDMxMDMyNTAwGwICBqkCAQEEEgwQMTAwMDAwMDUzMjkwMTAxNDAfAgIGqAIBAQQWFhQyMDE5LTA3LTAzVDA5OjI1OjI0WjAfAgIGqgIBAQQWFhQyMDE5LTA1LTMwVDEyOjQ1OjEwWjAfAgIGrAIBAQQWFhQyMDE5LTA3LTAzVDA5OjMwOjI0WjAlAgIGpgIBAQQcDBpva211c2ljaWFuLm1vbnRobHkudWt1bGVsZTCCAYcCARECAQEEggF9MYIBeTALAgIGrQIBAQQCDAAwCwICBrACAQEEAhYAMAsCAgayAgEBBAIMADALAgIGswIBAQQCDAAwCwICBrQCAQEEAgwAMAsCAga1AgEBBAIMADALAgIGtgIBAQQCDAAwDAICBqUCAQEEAwIBATAMAgIGqwIBAQQDAgEDMAwCAgauAgEBBAMCAQAwDAICBrECAQEEAwIBADAMAgIGtwIBAQQDAgEAMBICAgavAgEBBAkCBwONfqd7mU8wGwICBqcCAQEEEgwQMTAwMDAwMDU0MzEwNTkxMDAbAgIGqQIBAQQSDBAxMDAwMDAwNTMyOTAxMDE0MB8CAgaoAgEBBBYWFDIwMTktMDctMDNUMDk6MzA6MjRaMB8CAgaqAgEBBBYWFDIwMTktMDUtMzBUMTI6NDU6MTBaMB8CAgasAgEBBBYWFDIwMTktMDctMDNUMDk6MzU6MjRaMCUCAgamAgEBBBwMGm9rbXVzaWNpYW4ubW9udGhseS51a3VsZWxloIIOZTCCBXwwggRkoAMCAQICCA7rV4fnngmNMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYDVQQGEwJVUzETMBEGA1UECgwKQXBwbGUgSW5jLjEsMCoGA1UECwwjQXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMxRDBCBgNVBAMMO0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE1MTExMzAyMTUwOVoXDTIzMDIwNzIxNDg0N1owgYkxNzA1BgNVBAMMLk1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKXPgf0looFb1oftI9ozHI7iI8ClxCbLPcaf7EoNVYb/pALXl8o5VG19f7JUGJ3ELFJxjmR7gs6JuknWCOW0iHHPP1tGLsbEHbgDqViiBD4heNXbt9COEo2DTFsqaDeTwvK9HsTSoQxKWFKrEuPt3R+YFZA1LcLMEsqNSIH3WHhUa+iMMTYfSgYMR1TzN5C4spKJfV+khUrhwJzguqS7gpdj9CuTwf0+b8rB9Typj1IawCUKdg7e/pn+/8Jr9VterHNRSQhWicxDkMyOgQLQoJe2XLGhaWmHkBBoJiY5uB0Qc7AKXcVz0N92O9gt2Yge4+wHz+KO0NP6JlWB7+IDSSMCAwEAAaOCAdcwggHTMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyMDQwHQYDVR0OBBYEFJGknPzEdrefoIr0TfWPNl3tKwSFMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEeBgNVHSAEggEVMIIBETCCAQ0GCiqGSIb3Y2QFBgEwgf4wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNgYIKwYBBQUHAgEWKmh0dHA6Ly93d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5LzAOBgNVHQ8BAf8EBAMCB4AwEAYKKoZIhvdjZAYLAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAA2mG9MuPeNbKwduQpZs0+iMQzCCX+Bc0Y2+vQ+9GvwlktuMhcOAWd/j4tcuBRSsDdu2uP78NS58y60Xa45/H+R3ubFnlbQTXqYZhnb4WiCV52OMD3P86O3GH66Z+GVIXKDgKDrAEDctuaAEOR9zucgF/fLefxoqKm4rAfygIFzZ630npjP49ZjgvkTbsUxn/G4KT8niBqjSl/OnjmtRolqEdWXRFgRi48Ff9Qipz2jZkgDJwYyz+I0AZLpYYMB8r491ymm5WyrWHWhumEL1TKc3GZvMOxx6GUPzo22/SGAGDDaSK+zeGLUR2i0j0I78oGmcFxuegHs5R0UwYS/HE6gwggQiMIIDCqADAgECAggB3rzEOW2gEDANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwMjA3MjE0ODQ3WhcNMjMwMjA3MjE0ODQ3WjCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMo4VKbLVqrIJDlI6Yzu7F+4fyaRvDRTes58Y4Bhd2RepQcjtjn+UC0VVlhwLX7EbsFKhT4v8N6EGqFXya97GP9q+hUSSRUIGayq2yoy7ZZjaFIVPYyK7L9rGJXgA6wBfZcFZ84OhZU3au0Jtq5nzVFkn8Zc0bxXbmc1gHY2pIeBbjiP2CsVTnsl2Fq/ToPBjdKT1RpxtWCcnTNOVfkSWAyGuBYNweV3RY1QSLorLeSUheHoxJ3GaKWwo/xnfnC6AllLd0KRObn1zeFM78A7SIym5SFd/Wpqu6cWNWDS5q3zRinJ6MOL6XnAamFnFbLw/eVovGJfbs+Z3e8bY/6SZasCAwEAAaOBpjCBozAdBgNVHQ4EFgQUiCcXCam2GGCL7Ou69kdZxVJUo7cwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290LmNybDAOBgNVHQ8BAf8EBAMCAYYwEAYKKoZIhvdjZAYCAQQCBQAwDQYJKoZIhvcNAQEFBQADggEBAE/P71m+LPWybC+P7hOHMugFNahui33JaQy52Re8dyzUZ+L9mm06WVzfgwG9sq4qYXKxr83DRTCPo4MNzh1HtPGTiqN0m6TDmHKHOz6vRQuSVLkyu5AYU2sKThC22R1QbCGAColOV4xrWzw9pv3e9w0jHQtKJoc/upGSTKQZEhltV/V6WId7aIrkhoxK6+JJFKql3VUAqa67SzCu4aCxvCmA5gl35b40ogHKf9ziCuY7uLvsumKV8wVjQYLNDzsdTJWk26v5yZXpT+RN5yaZgem8+bQp0gF6ZuEujPYhisX4eOGBrr/TkJ2prfOv/TgalmcwHFGlXOxxioK0bA8MFR8wggS7MIIDo6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNjA0MjUyMTQwMzZaFw0zNTAyMDkyMTQwMzZaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOSRqQkfkdseR1DrBe1eeYQt6zaiV0xV7IsZid75S2z1B6siMALoGD74UAnTf0GomPnRymacJGsR0KO75Bsqwx+VnnoMpEeLW9QWNzPLxA9NzhRp0ckZcvVdDtV/X5vyJQO6VY9NXQ3xZDUjFUsVWR2zlPf2nJ7PULrBWFBnjwi0IPfLrCwgb3C2PwEwjLdDzw+dPfMrSSgayP7OtbkO2V4c1ss9tTqt9A8OAJILsSEWLnTVPA3bYharo3GSR1NVwa8vQbP4++NwzeajTEV+H0xrUJZBicR0YgsQg0GHM4qBsTBY7FoEMoxos48d3mVz/2deZbxJ2HafMxRloXeUyS0CAwEAAaOCAXowggF2MA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjAfBgNVHSMEGDAWgBQr0GlHlHYJ/vRrjS5ApvdHTX8IXjCCAREGA1UdIASCAQgwggEEMIIBAAYJKoZIhvdjZAUBMIHyMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wgcMGCCsGAQUFBwICMIG2GoGzUmVsaWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRhbmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNvbmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmljYXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wDQYJKoZIhvcNAQEFBQADggEBAFw2mUwteLftjJvc83eb8nbSdzBPwR+Fg4UbmT1HN/Kpm0COLNSxkBLYvvRzm+7SZA/LeU802KI++Xj/a8gH7H05g4tTINM4xLG/mk8Ka/8r/FmnBQl8F0BWER5007eLIztHo9VvJOLr0bdw3w9F4SfK8W147ee1Fxeo3H4iNcol1dkP1mvUoiQjEfehrI9zgWDGG1sJL5Ky+ERI8GA4nhX1PSZnIIozavcNgs/e66Mv+VNqW2TAYzN39zoHLFbr2g8hDtq6cxlPtdk2f8GHVdmnmbkyQvvY1XGefqFStxu9k0IkEirHDx22TZxeY8hLgBdQqorV2uT80AkHN7B1dSExggHLMIIBxwIBATCBozCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eQIIDutXh+eeCY0wCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAQBusKz9qnFvUhLPoCQs7iV7K9fbMhkhWsoenS9Q9l+yEFNrodzua3Q+QLxOcgqjdeEbvG+wnwT2LZJocKEpPcDJl6zE3C3y8G0ylMHXUrIxuQ3uBb1G9i8QgOBm5TZvRp4VkjKE7CrGE/2+MdgiIb9SDvqOc02DhrB30zLF+cDOJsWGmX6I0t8E+iMnbBstBtjrMmrdltwlZcoZZa+UZphOQhNMM85K+6w9tXe4tMIFAsFjjDdrgfAhSCvy/XNGNn6sQ7CgX5XqXFzRGLW02O/11dZA/eGom72CuWbc7FcjU8HiK/7RmvT61/BtHJ5uicwFB7O8twI20MYhHR2pigwz"}

data = {
    "itunes_receipt": json.dumps(ret)
}

# ret = requests.post("http://127.0.0.1:8001/v9/subscription/iap/check", headers=headers, json=data)
# print(ret.content)
# print(ret.json())

lis = list()
print(lis[0])
