# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ServiceRegistry.protos import service_registry_pb2 as service__registry__pb2


class ServiceRegistryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegServer = channel.unary_unary(
        '/example.ServiceRegistry/RegServer',
        request_serializer=service__registry__pb2.Request.SerializeToString,
        response_deserializer=service__registry__pb2.Response.FromString,
        )
    self.LogoutService = channel.unary_unary(
        '/example.ServiceRegistry/LogoutService',
        request_serializer=service__registry__pb2.Request.SerializeToString,
        response_deserializer=service__registry__pb2.Response.FromString,
        )


class ServiceRegistryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LogoutService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceRegistryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegServer': grpc.unary_unary_rpc_method_handler(
          servicer.RegServer,
          request_deserializer=service__registry__pb2.Request.FromString,
          response_serializer=service__registry__pb2.Response.SerializeToString,
      ),
      'LogoutService': grpc.unary_unary_rpc_method_handler(
          servicer.LogoutService,
          request_deserializer=service__registry__pb2.Request.FromString,
          response_serializer=service__registry__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'example.ServiceRegistry', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
